apiVersion: v1
kind: Namespace
metadata:
  name: flux

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: flux
  namespace: flux
spec:
  chart: flux
  repo: https://charts.fluxcd.io
  version: ${version}
  targetNamespace: flux
  set:
    git.url: ${git_url}
