---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: helm-operator
  namespace: kube-system
spec:
  chart: helm-operator
  repo: https://charts.fluxcd.io
  version: ${version}
  targetNamespace: flux
  set:
    helm.versions: v3
